name: Url health check

on: 
  push:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check URL health
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://blog-list-enzoacostab.vercel.app/

